name: Docker Test
on: [push]
jobs:
    test-docker-container:
        runs-on: ubuntu-latest
        container:
            image: node:13
            env:
                NODE_ENV: test
            ports:
                - 80
        steps:
            - name: Display Node.js version
              run: |
                  node -v
                  cat /etc/os-release
