name: Eights Workflow
on:
    workflow_dispatch:
        inputs:
            nanumber:
                description: "Your number"
                type: number
                required: true
                default: "5"
jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Print some text
              run: echo "Hello, ${{ github.event.inputs.name }}!"
