name: First Workflow
on: [push]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Print some text
              run: echo "Hello, World!"

            - name: Run a second multiline command
              run: |
                  python -V
                  ruby -V
