name: Fourteenth Workflow
on: workflow_dispatch
jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - name: Chache Node.js modules
              id: cache-node-modules-step
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: node-cache_file
            - name: Show cache step results
              run: |
                  echo "${{ toJson(steps.cache-node-modules-step.outputs) }}"
            - name: Install Node.js modules
              run: npm install
