name: Seventh Workflow
on:
    schedule:
        - cron: "*/5 * * * *"
jobs:
    show_datetime:
        runs-on: ubuntu-latest
        steps:
            - name: Show current date and time
              run: date
