name: Seventeenth Workflow
on:
    workflow_dispatch:
        inputs:
            title:
                description: "The title to use in the workflow"
                required: false
                type: string
                default: "Default Test Title"
jobs:
    call-workflow:
        uses: "./.github/workflows/workflow.yml"
        with:
            title: ${{ github.event.inputs.title }}
    call-external-workflow:
        uses: "GreenDevOps/workflows/.github/workflows/external_workflow.yml@main"
        secrets:
            PASSWORD: ${{ secrets.PASSWORD }}
    display-output:
        needs: [call-workflow]
        runs-on: ubuntu-latest
        steps:
            - name: Display output from reusable workflow
              run: 'echo "The current date and time is: ${{ needs.call-workflow.outputs.date }}"'
