name: Seventeenth Workflow
on:
    workflow_dispatch:
        inputs:
            title:
                description: "The title to use in the workflow"
                required: false
                type: string
                default: "Default Test Title"
jobs:
    call-workflow:
        uses: "./.github/workflows/workflow.yml"
        with:
            title: ${{ github.event.inputs.title }}
    call-external-workflow:
        uses: "GreenDevOps/workflows/.github/workflows/external_workflow.yml@main"
        secrets:
            PASSWORD: ${{ secrets.PASSWORD }}
