name: Sixteenth Workflow
on: [push]
run-name: Using Matrix Strategy to Run Jobs in Parallel
jobs:
    test-matrix-job:
        strategy:
            matrix:
                node-version: [14, 16, 18]
        runs-on: ubuntu-latest
        steps:
            - run: node -v
            - uses: actions/node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: node -v
