name: Ten Workflow
on: [push]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Contexts and Expressions
              id: contexts-and-expressions
              run: |
                  echo "${{ toJson(github) }} "
                  echo "${{ toJson(runner) }} "
                  echo "${{ toJson(job) }} "
                  echo "${{ toJson(steps) }} "
                  echo "${{ toJson(secrets) }} "
