name: Thirteenth Workflow
on: [push]

jobs:
    # success() failure() cancelled() skipped() always()
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Run a command that cancelled
              run: sleep 30
            - name: Runs on cancelled
              if: ${{ cancelled() }}
              run: echo "This job was cancelled"
            - name: Runs on success
              if: ${{ success() }}
              run: echo "This job was successful"
            - name: Runs on failure
              if: ${{ failure() }}
              run: echo "This job failed"
            - name: Runs always
              if: ${{ always() }}
              run: echo "This job always runs"
    job2:
        runs-on: ubuntu-latest
        needs: job1
        if: ${{ failed() }}
        steps:
            - name: Run a command that fails
              run: echo "Job1 was failed"
