name: Reusable Workflow
on:
    workflow_call:
        inputs:
            title:
                description: "The title to use in the workflow"
                required: false
                type: string
                default: "Default Test Title"

jobs:
    conslole-log:
        runs-on: ubuntu-latest
        steps:
            - name: Print Title
              run: 'echo "The title is: ${{ github.event.inputs.title }}"'
