name: Reusable Workflow
on:
    workflow_call:
        inputs:
            title:
                description: "The title to use in the workflow"
                required: false
                type: string
                default: "Default Test Title"
        outputs:
            date:
                description: "The current date and time"
                value: ${{ jobs.generate-output.outputs.date }}

jobs:
    conslole-log:
        runs-on: ubuntu-latest
        steps:
            - name: Print Title
              run: 'echo "The title is: ${{ github.event.inputs.title }}"'
    generate-output:
        runs-on: ubuntu-latest
        outputs:
            date: ${{ steps.set-output.outputs.date }}
        steps:
            - run: echo "date=$(date)" >> $GITHUB_OUTPUT
              id: set-output
